/**
 * Configuration that only exists after the infrastructure does.
 *
 * The user pool ID, client ID and login URL are generated by CloudFormation
 * at deploy time, so they cannot be baked into a build that happens first.
 * The stack writes them to /config.json next to index.html; the app fetches
 * that before rendering. One build artifact works in any environment.
 */

export interface RuntimeConfig {
  environment: string;
  region: string;
  userPoolId: string;
  userPoolClientId: string;
  /** Base URL of the hosted login pages, e.g. https://auth.oddssea.xyz */
  cognitoDomain: string;
}

let cached: RuntimeConfig | null = null;

export async function loadRuntimeConfig(): Promise<RuntimeConfig> {
  if (cached) return cached;

  // Deployed: the file the stack uploaded.
  const response = await fetch('/config.json', { cache: 'no-store' }).catch(() => null);
  if (response?.ok) {
    cached = (await response.json()) as RuntimeConfig;
    return cached;
  }

  // Local `npm run dev`: no deployed config.json — read web/.env.local,
  // populated once from the stack outputs (infra/README.md, Increment B).
  const fromEnv: RuntimeConfig = {
    environment: 'local',
    region: import.meta.env.VITE_REGION ?? '',
    userPoolId: import.meta.env.VITE_USER_POOL_ID ?? '',
    userPoolClientId: import.meta.env.VITE_USER_POOL_CLIENT_ID ?? '',
    cognitoDomain: import.meta.env.VITE_COGNITO_DOMAIN ?? '',
  };

  const missing = Object.entries(fromEnv)
    .filter(([key, value]) => key !== 'environment' && !value)
    .map(([key]) => key);
  if (missing.length > 0) {
    throw new Error(
      `Could not load /config.json, and web/.env.local is missing: ${missing.join(', ')}. ` +
        'See infra/README.md — "Running the app locally".',
    );
  }

  cached = fromEnv;
  return cached;
}
