/**
 * Configuration that only exists after the infrastructure does.
 *
 * The user pool ID, client ID and login URL are generated by CloudFormation
 * at deploy time, so they cannot be baked into a build that happens first.
 * The stack writes them to /config.json next to index.html; the app fetches
 * that before rendering. One build artifact works in any environment.
 */

export interface RuntimeConfig {
  environment: string;
  region: string;
  userPoolId: string;
  userPoolClientId: string;
  /** Base URL of the hosted login pages, e.g. https://auth.oddssea.xyz */
  cognitoDomain: string;
  /** Base URL of the API, e.g. https://api.oddssea.xyz */
  apiUrl: string;
}

let cached: RuntimeConfig | null = null;

export async function loadRuntimeConfig(): Promise<RuntimeConfig> {
  if (cached) return cached;

  // Deployed: the file the stack uploaded.
  //
  // A 200 is NOT enough to conclude the file exists. Vite's dev server (and
  // the deployed CloudFront error mapping, by design) answers unmatched
  // paths with index.html and a 200 — so a missing config.json arrives as
  // HTML wearing a success status. Check the content type, and still guard
  // the parse: the whole point of this branch is to fall through cleanly to
  // the local .env.local path below when the file is not really there.
  const response = await fetch('/config.json', { cache: 'no-store' }).catch(() => null);
  if (response?.ok && response.headers.get('content-type')?.includes('application/json')) {
    try {
      cached = (await response.json()) as RuntimeConfig;
      return cached;
    } catch {
      // Malformed JSON — fall through rather than crash the app on boot.
    }
  }

  // Local `npm run dev`: no deployed config.json — read web/.env.local,
  // populated once from the stack outputs (infra/README.md, Increment B).
  const fromEnv: RuntimeConfig = {
    environment: 'local',
    region: import.meta.env.VITE_REGION ?? '',
    userPoolId: import.meta.env.VITE_USER_POOL_ID ?? '',
    userPoolClientId: import.meta.env.VITE_USER_POOL_CLIENT_ID ?? '',
    cognitoDomain: import.meta.env.VITE_COGNITO_DOMAIN ?? '',
    apiUrl: import.meta.env.VITE_API_URL ?? '',
  };

  const missing = Object.entries(fromEnv)
    .filter(([key, value]) => key !== 'environment' && !value)
    .map(([key]) => key);
  if (missing.length > 0) {
    throw new Error(
      `Could not load /config.json, and web/.env.local is missing: ${missing.join(', ')}. ` +
        'See infra/README.md — "Running the app locally".',
    );
  }

  cached = fromEnv;
  return cached;
}
